apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    http:
      addr: :5000
      {{- if .Values.tls.enabled }}
      tls:
        certificate: /certs/tls.crt
        key: /certs/tls.key
      {{- end }}
      headers:
        X-Content-Type-Options: [nosniff]
    {{- if .Values.auth.enabled }}
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    {{- end }}
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
