{{- if and .Values.auth.enabled .Values.auth.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
type: Opaque
data:
  # base64 of your htpasswd file content under key "htpasswd"
  htpasswd: ""
{{- end }}
