{{- if and .Values.tls.enabled .Values.tls.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
type: kubernetes.io/tls
data:
  # base64 of your cert and key (you'll kubectl create secret tls ... instead, see install steps)
  tls.crt: ""
  tls.key: ""
{{- end }}
